branch-defaults:
  default:
    environment: null
    group_suffix: null
  main:
    environment: north-star-market-dev
global:
  application_name: north-star-market
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 3.2 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
